init_epoch: 1
init_lr: 0.1
init_milestones: 
  - 60
  - 120
  - 170
init_lr_decay: 0.1
init_weight_decay: 0.0005

epochs: 1
lrate: 0.1
milestones: 
  - 40
  - 70
lrate_decay: 0.1
batch_size: 128
weight_decay: 0.0002
num_workers: 8
